### ISSUE TITLE
Create a console interface for commandline implementations

### ISSUE THREAD

**Issue by ilhnctn** [biberlabs/zf2-boilerplate#24] opened 2015-11-22 19:57 UTC

**Comment by hkulekci** [comment] 2015-11-22 20:01
Are there more information in this issue? What will you do? What do you think about structure? Maybe you could add some link about best practices. @ilhnctn

**Comment by ilhnctn** [comment] 2015-11-22 20:04
I would explain the scenario in mind but just at that time faced an installition problem, i will explain the plan in a moment. Also you can kindly share your opinions to improve a better product @hkulekci

**Comment by edigu** [comment] 2015-12-06 12:43
Dupe of last task of #5

**Closed by edigu** 2015-12-06 12:43 UTC
